name: ExoticGarden
version: ${project.version}
authors:
  - "TheBusyBiscuit"
  - "Narcissu14"
  - "1798643961"
  - "NCBPFluffyBear"
  - "balugaq"

description: A Slimefun Addon that adds new Plants and dishes to the game
website: https://github.com/balugaq/ExoticGardenComplex

api-version: 1.18
main: io.github.thebusybiscuit.exoticgarden.ExoticGarden

depend:
  - Slimefun
  - GuizhanLibPlugin

softdepend:
  - Sanity
  - Residence
  - FluffyMachines

commands:
  exotic:
    description: ExoticGarden base command
    usage: The ExoticGarden version you have installed does not seem to be compatible with your server setup. Check your console for more detailed info.
permissions:
  exoticgarden.admin:
    description: admin
    default: op